@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class "AnnouncementController" as Actrl{
    +addAnnouncementSold(AnnouncementSold)

}

class "ImportController" as ctrl{
    +JFileChooser()
    +addLegacyFile(file, filePath)
    -validateCSV(file)
    -validateEmpty(file)

}

class "ImportUI" as UI{


}

class AnnouncementRepository {
    -List<AnnouncementSold>

    +addAnnouncementSold(AnnouncementSold)
}

class "AnnouncementSold" as announcement{
    - id
    - comission
    - price
    - date
    - businessType
    - property
    - agent
    - List<Order> orderList
    - ContractDuraction=0
    - salePrice
    - saleDate
    - agency
}

class "ExternalModuleCSV" as csv{
    -sid
    - owner_name
    - owner_passportNum
    - owner_TIN
    - owner_email
    - owner_phone
    - property_type
    - property_area
    - property_location
    - property_distanceFromCenter
    - property_numberBedrooms
    - property_numberBathrooms
    - property_pnumParking
    - property_centralHeating
    - property_airconditioned
    - property_basement
    - property_loft
    - property_sunExposure
    - property_requested_sale_rent_price
    - property_sale_rent_price
}

class "ExternalModuleAdapterCSV" as adapter{
    -List<ExternalModuleCSV>
    +readFile(filepath)
    -add(ExternalModuleCSV)
    +add(AnnouncementSold)

}

interface ExternalModule{
    readFile(filepath)
}

UI ..> ctrl
ctrl ..> adapter
ctrl ..> ExternalModuleCSV
ctrl ..> announcement


adapter -> csv : contains >
csv -> announcement : creates >
adapter --> Actrl: makes uses of >
Actrl -> AnnouncementRepository: records in >
adapter <|.. ExternalModule

@enduml