@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US004 - System Sequence Diagram (SSD)

autonumber

actor "Owner" as Owner
participant ":System" as System

activate Owner




    Owner -> System : asks to  submit a request for listing a property sale or rent
    activate System

    System --> Owner : requests Owner data (name, phone number and email)
    deactivate System

    Owner -> System : types requested data
    activate System

        System --> Owner : requests data from the property (select the type of business and property characteristics \nand types the requested price)
    deactivate System

    Owner -> System : types requested data
    activate System

    System --> Owner : shows a list of agencies and ask to select
        deactivate System

        Owner -> System : selects the agency
        activate System

        System --> Owner : asks if wants to choose agent
    deactivate System

    Owner -> System : asks to choose the agent
    activate System

        System --> Owner : lists the agents
    deactivate System

    Owner -> System : selects the agent
    activate System

        System --> Owner : shows the data and agent chosed
    deactivate System

    Owner -> System : Submits the data and agent
    activate System

        System --> Owner : Shows success message
    deactivate System
@enduml