@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


skinparam classAttributeIconSize 0

skinparam groupInheritance 1


hide circle
hide methods

title Domain Model US001 - Display listed properties


class Announcement{
id
listingDate
comission
requestPrice
}

class "Unregistered User" as user{
}

class Property{
propertyID
type
location
area
distanceCenter
propertyDescription
photograph
}

class Land{}

class Apartment{
numberBedrooms
numberBath
numberParking
equipment
}

class House{
numberBedrooms
numberBath
numberParking
equipment
basement
loft
sunExposure
}



user "1" -right- "*" Announcement : Displays >
Property "1" -left- "1" Announcement : is a physical part of >

class Land extends Property
class Apartment extends Property
class House extends Property













@enduml