@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber
title US002 - System Sequence Diagram (SSD)

actor "Owner" as Owner
actor "Agent" as Agent
participant "System" as System


activate Owner
activate Agent
activate System

Owner -> Agent : provides sale data
Agent -> System : asks to publish a sale
System --> Agent : requests necessary data about the property
Agent -> System : provides the necessary data
System --> Agent : requests a type of comission
Agent -> System : selects the type
System --> Agent : requests a value for comission
Agent -> System : types the value and confirm
System --> Agent : Shows all data and requests confirmation
Agent -> System : confirms the data

System --> System : publishes sale
System --> Agent : informs operation success



@enduml