@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class "AnnouncementController" as ctrl{
    +getOrderListDTO(AnnouncementDTO announcementDTO)
    +getListAnnouncementAvailableDTOForAgent()
    +sendOrderResultsViaEmail(List<OrderDTO> orders, AnnouncementDTO announcement)


}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getAnnouncementRepository()
}

class AnnouncementRepository {
    + getAgentAnnouncements(String email)

}

class AnnouncementAvailable{
    +getOrderList()
}
class order{
    +order.setstate()
}
class OrderDTO{
    +orderDTO.setstate()
}


class "ApplicationSession" as appSession {
    +getInstance()
    +getCurrentSession()

}



class Agent {
+int id
+String name
+long phoneNumber
+int taxNumber
+String password
+int civilNumber
+String address
+String mail

}

class AgentDTO {
+int id
+String name
+long phoneNumber
+int taxNumber
+String password
+int civilNumber
+String address
+String mail

}
class AgentMapper {
+toDTO(Agent)

}

class "UserSession" as userSession {
    +getEmail()

}

class processOrders{
+ acceptOrder()
+ declineOrder()
}



class AnnouncementAvailable {
    -Int id
    -Date date
    -Double comission
    -Double price
    -Property Property
    -Agent agent
    -List<Order> Order

}

class ListAcceptOrDeclineOffersUI {
}



class order{
    -clientEmail
    -value

}

class AnnouncementDTO{
    -Int id
    -Date date
    -Double comission
    -Double price
    -Property Property
    -Agent agent
    -List<Order> Order
    }

    class OrderDTO{
        int id
        String clientEmail;
        double value;
        Date date;
        int state;
        }

    class AnnouncementMapper{
        +toDto(ListAnnouncementAvailable)
        +toDto(AnnouncementAvailable)
        }

    class OrderMapper{
         +toDto(OrderList)
         +toDto(Order)
                }

ListAcceptOrDeclineOffersUI .> ctrl

ctrl .-> AnnouncementRepository
ctrl .-> Repositories
ctrl .-> appSession
ctrl .-> AnnouncementAvailable
ctrl .-> userSession
ctrl .-> AnnouncementMapper
ctrl .-> AgentMapper
ctrl .-> AgentDTO
ctrl .-> OrderMapper
ctrl .-> AnnouncementDTO
ListAcceptOrDeclineOffersUI .> AnnouncementDTO



Repositories -> Repositories : instance

AnnouncementRepository "1"-->"*" AnnouncementAvailable : AnnouncementAvailable
AnnouncementAvailable "1" --> "*" order : contains
appSession -> userSession : userSession

AnnouncementMapper .-> AnnouncementAvailable
AnnouncementMapper .-> AnnouncementDTO

OrderMapper .-> order
OrderMapper .-> OrderDTO

UserSession .-> Agent
UserSession "1" --> "*" Agent : gets  Agent email

order "2" --> "*" processOrders : can be evaluated

Agent .-> processOrders
Agent "3" --> "*" processOrders : processes the orders






@enduml